---
# THIS IS SAMPLE CONFIG FILE, USED FOR LOCAL DEVELOPMENT
# Logging map partially mimics configuration of uber/zap Config structure
# See  https://pkg.go.dev/go.uber.org/zap
logging:
  # Development key puts the logger in development mode, which changes the behavior of DPanicLevel and takes stacktraces more liberally.
  development: true
  # level: info
  level: debug
  encoding: console
  # encoding: json
  disable_caller: false
  disable_stacktrace: false
  disable_color: false
  # output_paths: ["stdout", "/tmp/1.log"]
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]

database:
  hostname: postgresql
  port: 5432
  name: publications
  username: publications
  password: publications
  sslmode: disable
  log_level: debug
  min_connections: 2
  max_connections: 50

server:
  address: ":8080"
  request_timeout: 60

rss_api_url: http://rss-feeds-api/feeds